name: tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: test on ubuntu-latest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest dove
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "dfinance/move-tools"
          version: "tags/0.9.10"
          file: test-runner-linux

      - name: set executable permissions
        run: sudo chown runner ./dove && chmod +x ./dove

      - name: Test
        run: ./dove test
